### ISSUE TITLE
Compiling error under Xcode 11 beta 4

### ISSUE THREAD

**Issue by arigatou1985** [iZettle/Form#114]
# Expected Behavior 
The framework should be compilable with Xcode 11 beta 4.

# Current Behavior 
The Xcode 11 beta 4 fails to compile with the latest released source code i.e., v1.10.1.
 
# Steps to Reproduce 
Compile a project with dependency (using cocoapods) to Form, Flow and Presentation.

## Context  
Nothing particular. Xcode 11 beta 4 simply fails to compile the source code in Form.
 
* Operating Version: 
MacOS X 10.14.6

* Swift version: 
 5.1

## Failure Logs 
[compiler_error_log.txt](https://github.com/iZettle/Form/files/3451693/compiler_error_log.txt)

Please include any relevant log snippets or files here.

**Comment by mansbernhardt** [comment]
This looks similar to an earlier crash that I reported that should have been solved in the latest seeds. See https://bugs.swift.org/plugins/servlet/mobile#issue/SR-10728

**Comment by arigatou1985** [comment]
> This looks similar to an earlier crash that I reported that should have been solved in the latest seeds. See https://bugs.swift.org/plugins/servlet/mobile#issue/SR-10728

Thanks a lot for the info, Måns. I just tried to build the project using Xcode 11 beta 5, the issue has indeed been resolved, Form framework can be now built error-free.
