### ISSUE TITLE
`TableKit.viewForEmptyTable` behavior

### ISSUE THREAD

**Issue by mansbernhardt** [iZettle/Form#13]
`TableKit.viewForEmptyTable` has a hardcoded inset of 15 points as well as pinning left and right
 
`TableKit.viewForEmptyTable` should instead embed the view to cover the table view completely. The previous behavior could be easily achieved by embedding the view similar to how the implementation is doing today:

`UIView(embeddedView: getEmptyView(()), edgeInsets: UIEdgeInsets(horizontalInset: 15, verticalInset: 15), pinToEdges: [.left, .right])`
 
If we go forward with this change `TableKit.viewForEmptyTable` will have get a new behavior and will break current clients. My suspicion is that the iZettle app is the only one. We can also add a new delegate with a new name, and deprecate the old one.

**Comment by fennecos** [comment]
Should we close this issue?

**Comment by nataliq** [comment]
Yes. This change is available in v1.2.0
