### ISSUE TITLE
Empty state replacement of TableKit

### ISSUE THREAD

**Issue by moglistree** [iZettle/Form#99]
# Expected Behavior 
 
When the second empty state view is set the first one should be removed. 
Screenshot:
<img width="372" alt="correct" src="https://user-images.githubusercontent.com/15359415/55488719-deecf180-5630-11e9-8e8c-21e0fe6ac4dc.png">

# Current Behavior 
 
Views that are set for empty state are overlapping.
Screenshot:
<img width="375" alt="Screenshot 2019-04-03 at 16 36 21" src="https://user-images.githubusercontent.com/15359415/55488082-a7317a00-562f-11e9-9c0b-84b47d304489.png">
 
# Steps to Reproduce 
 
1. Create a TableKit instance and set a viewForEmptyTable
2. Set a second viewForEmptyTable
 
## Context  
 
User an empty state view to present a spinner while a request is fetching data and then try to substitute it with an empty state view when the request fails or returns no data

* Operating Version: Any iOS version
* Swift version: 4.1

## Proposed solution
Add functionality in the method viewForEmptyTable to remove the previously added view example before 

`self.view.embedAutoresizingView(emptyView)`

add

`emptyView.tag = 666`
` self.view.subviews.first(where: { $0.tag == 666 })?.removeFromSuperview()`

**Comment by nataliq** [comment]
The delegate for empty state view has a clean up block that removes the added view:
`bag += { currentView?.removeFromSuperview() }` and according to the Delegate documentation `If a callback was already set, it will be unset before the new callback is set.`. I think if I understand correctly, the current solution we have tries to address this problem and there might be a bug with it that we need to address. Do you think that's the case?

**Comment by moglistree** [comment]
Good question. I have overlooked `bag += { currentView?.removeFromSuperview() }` and it is correct that the problem looks like is in the trigger of the clean up and not in absence of the cleanup.

**Comment by nataliq** [comment]
The problem seems to be introduced with the deprecation of `public lazy var viewForEmptyTable: Delegate<(), UIView>` and its translation to a function that will create a new instance every time `viewForEmptyTable` is called. This test reproduces it:
```swift
func testEmptyStateView_setNewView_oldViewIsRemoved() {
        let emptyTable: Table<Int, Int> = Table(sections: [(1, [])])
        let tableView = TableKit(table: emptyTable, bag: bag) { _, _ in UITableViewCell() }

        let oldEmptyStateView = UIView()
        bag += tableView.viewForEmptyTable().set { _ in
            return oldEmptyStateView
        }

        XCTAssertNotNil(oldEmptyStateView.superview)

        let newEmptyStateView = UIView()
        bag += tableView.viewForEmptyTable().set { _ in
            return newEmptyStateView
        }

        XCTAssertNotNil(newEmptyStateView.superview)
        XCTAssertNil(oldEmptyStateView.superview)
    }
```
where if you do this instead the bug is not reproducible:
func testEmptyStateView_setNewView_oldViewIsRemoved() {
        let emptyTable: Table<Int, Int> = Table(sections: [(1, [])])
        let tableView = TableKit(table: emptyTable, bag: bag) { _, _ in UITableViewCell() }

        let oldEmptyStateView = UIView()
        let viewForEmptyTable = tableView.viewForEmptyTable()
        bag += viewForEmptyTable.set { _ in
            return oldEmptyStateView
        }

        XCTAssertNotNil(oldEmptyStateView.superview)

        let newEmptyStateView = UIView()
        bag += viewForEmptyTable.set { _ in
            return newEmptyStateView
        }

        XCTAssertNotNil(newEmptyStateView.superview)
        XCTAssertNil(oldEmptyStateView.superview)
    }
```

**Comment by moglistree** [comment]
Did some experiments and prototyped some potential solutions what I came up with is to update to since the method already sued the currentView and this was the most minimal change I could do that passes the tests and fixes the issue any feedback is welcomed:
```
public func viewForEmptyTable(fadeDuration: TimeInterval = 0.15) -> Delegate<(), UIView> {
        return Delegate { [weak self] getEmptyView in
            let bag = DisposeBag()
            guard let `self` = self else { return bag }

            bag += self.atOnce().onValue { table in
                if let prevView = self.currentViewForEmptyTable {
                    self.currentViewForEmptyTable = nil
                    UIView.animate(withDuration: fadeDuration,
                                   animations: { prevView.alpha = 0 },
                                   completion: { _ in prevView.removeFromSuperview()  })
                }

                if table.isEmpty {
                    let emptyView = getEmptyView(())
                    emptyView.alpha = 0
                    self.view.embedAutoresizingView(emptyView)
                    self.view.sendSubview(toBack: emptyView)
                    self.currentViewForEmptyTable = emptyView
                    UIView.animate(
                        withDuration: fadeDuration,
                        delay: fadeDuration,
                        options: UIViewAnimationOptions.curveLinear,
                        animations: { emptyView.alpha = 1 }
                    )
                }
            }

            bag += { self.currentViewForEmptyTable?.removeFromSuperview() }

            return bag
        }
    }
    private var currentViewForEmptyTable: UIView?
```

**Comment by nataliq** [comment]
This will work and pass the test. I think we should add few more tests though because my suspicion here is that the previously allocated delegate won’t be deallocated and will result in a memory leak. 

Similar approach to this one taking care of the memory will be to store the delegate. But if we take a step back and look at the initial solution, I think I’m in flavor of that one with the lazy var instead. We will need to expose a public variable for the fade duration but I think that’s fine. Then the only remaining question will be how to handle the versioning of the API properly. We haven’t done a major release for a while and we can use it to remove some deprecated APIs so maybe that’s an option?

**Comment by mansbernhardt** [comment]
Perhaps this should have been like this from the start?

```swift
lazy viewForDurationForEmptyTable: Delegate<(), (view: UIView, duration: TimeInterval)> = { ... } () 
```

Not sure if we can use above as private and add a public wrapper such as this?

```swift
func viewForEmptyTable(fadeDuration: TimeInterval = 0.15) -> Delegate<(), UIView> {
    return Delegate { getEmptyView in 
         return self.viewForDurationForEmptyTable.set { 
             (view: getEmptyView(), duration)
        } 
   }
}
```

But it might not behave as expected? E.g. the delegates isSet might not correctly reflect was going on?

**Comment by moglistree** [comment]
Will test it out looks like a solid approach to the problem
